import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ColorModeProvider from "@/components/ColorModeProvider";

const geistSans = Geist({ subsets: ["latin"] });
const geistMono = Geist_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Js Taskboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          {/* Theme + CssBaseline sono gestiti dal provider client */}
          <ColorModeProvider>
            {children}
          </ColorModeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}